Feature/where filter
embedchain/embedchain pull request #518
Opened 2023-08-31 03:43 UTC by sw8fbar

## Description

Options to add where_filter on the retrieve_from_database function on embedchain.py. The options can be included in the QueryConfig or provided when the .query or .chat functions are called on EmbedChain or its subclasses. 

Fixes # 395

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

```
from string import Template
from embedchain import App
from embedchain.config import ChatConfig, QueryConfig
from langchain.memory import ChatMessageHistory

app = App()
# add data
app.add("test-abcd", 'text', metadata={"type": "alpha"})
app.add("test-23232331121212", 'text', metadata={"type": "num"})

# test for where_filter in query / chat
print({"type": "alpha"}, app.retrieve_from_database("return data", QueryConfig(), where_filter={"type": "alpha"}))
print({"type": "num"}, app.retrieve_from_database("return data", QueryConfig(), where_filter={"type": "num"}))

# test for where_filter in QueryConfig
queryconfig = QueryConfig(where_filter={"type": "alpha"})
print({"type": "alpha"}, app.retrieve_from_database("return context",queryconfig))
queryconfig = QueryConfig(where_filter={"type": "num"})
print({"type": "num"},app.retrieve_from_database("return context",queryconfig))

# test for where_filter in ChatConfig
chatconfig = ChatConfig(where_filter={"type": "alpha"})
chatconfig.set_history(ChatMessageHistory())
print({"type": "alpha"},app.retrieve_from_database("return data", chatconfig))
chatconfig = ChatConfig(where_filter={"type": "num"})
chatconfig.set_history(ChatMessageHistory())
print({"type": "num"}, app.retrieve_from_database("return data", chatconfig))
```

Please delete options that are not relevant.

- [X] Test Script (please provide)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Made sure Checks passed

2023-08-31 14:04 UTC, sw8fbar commented
@cachho please review if this meets your needs

2023-09-03 18:51 UTC, cachho commented
I think this most certainly needs a unit test

2023-09-04 08:33 UTC, cachho requested changes
Other than that it looks good.

2023-09-04 08:33 UTC, cachho commented on embedchain/embedchain.py
> +            where = {"app_id": self.config.id}
note the `if`, it can't be in the same block as the supplied `where` filters

2023-09-04 13:23 UTC, sw8fbar commented on embedchain/embedchain.py
> +            where = {"app_id": self.config.id}
Made requested changes. 
`
       if where_filter is not None:
            where = where_filter
        elif config is not None and config.where_filter is not None:
            where = config.where_filter

        if self.config.id is not None:
            where.update({"app_id": self.config.id})
`

2023-09-04 13:25 UTC, sw8fbar commented
Made requested changes. 
 ```
 if where_filter is not None:
            where = where_filter
        elif config is not None and config.where_filter is not None:
            where = config.where_filter

        if self.config.id is not None:
            where.update({"app_id": self.config.id})
```

2023-09-04 13:28 UTC, cachho approved these changes
Looks good. Do you think you will add unit tests?

2023-09-04 13:30 UTC, sw8fbar commented
I think it should be the following though. I can push this change if you agree

      ```
       if where_filter is not None:
           where = where_filter
       elif config is not None and config.where_filter is not None:
           where = config.where_filter
       else:
           where = {}

       if self.config.id is not None:
           where.update({"app_id": self.config.id})
```

2023-09-04 13:36 UTC, cachho commented
> I am working on it. Just struggling a bit to get it to work. My approach was to test if the parameters are passed to the retrieve_from_database function. But I am not sure that is enough.

I think that will do for now. I think it's technically possible to just insert vectors with metadata, and then you should also be able to search with a vector, and see if the result is what you expect. But I don't know how well Chroma exposes this stuff, and we don't want to write a test suite for chroma.

2023-09-04 17:14 UTC, sw8fbar commented
> > I am working on it. Just struggling a bit to get it to work. My approach was to test if the parameters are passed to the retrieve_from_database function. But I am not sure that is enough.
> 
> I think that will do for now. I think it's technically possible to just insert vectors with metadata, and then you should also be able to search with a vector, and see if the result is what you expect. But I don't know how well Chroma exposes this stuff, and we don't want to write a test suite for chroma.

Added the Unit tests

2023-09-04 20:00 UTC, taranjeet approved these changes

2023-09-04 20:35 UTC, sw8fbar commented on embedchain/apps/PersonApp.py
> +    def chat(self, input_query, config: ChatConfig = None, dry_run=False, where_filter=None):
> Hey @sw8fbar , can you please update the name to `where` instead of `where_filter`?

Done.

2023-09-04 20:49 UTC, taranjeet commented
The PR looks good. Thanks @sw8fbar for your contribution.

2023-09-04 20:50 UTC, merged

2023-09-04 20:51 UTC, taranjeet commented
@sw8fbar : Do you want to create a new PR where you add the documentation for this change as well?

2023-09-04 20:56 UTC, sw8fbar commented
> @sw8fbar : Do you want to create a new PR where you add the documentation for this change as well?

Sure. Give me a few

2023-09-04 21:09 UTC, sw8fbar commented
> > @sw8fbar : Do you want to create a new PR where you add the documentation for this change as well?
> 
> Sure. Give me a few

Added pull request #547